FROM debian:bullseye

RUN apt-get update
RUN	apt-get upgrade -y
RUN	apt-get install mariadb-server -y


COPY conf/mariadb.conf /etc/mysql/mariadb.conf.d/50-server.cnf
RUN copy script.sh .
RUN chomd +x /script.sh
RUN ./script.sh
CMD ["tail", "-f"]
