FROM debian:bullseye

RUN	apt-get update
RUN	apt-get upgrade -y
RUN	apt-get install nginx openssl -y

#now we need to add a folder to store the certificate and the key for secure connection 
RUN mkdir -p /etc/nginx/ssl
# here i need to replace the CERT_ with the who is in the .envfile => /etc/ssl/certs/nginx-selfsigned.crt
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=MO/L=KH/O=1337/OU=student/CN=sharrach.42.ma"
# RUN rm -r etc/nginx/sites-available/default
COPY conf/default /etc/nginx/sites-available/default
RUN chmod 755 /var/www/html
# RUN chown -R www-data:www-dat /var/www/html

CMD ["nginx", "-g", "daemon off;"]

